### ISSUE TITLE
GitHub integration seems broken

### ISSUE THREAD

**Issue by Griefed** [ErdbeerbaerLP/Curseforge-Bot#33]
Hey there ErdbeerbaerLP,

I'm in the process of writing a docker container for Curseforge-Bot and when testing out the GitHub Integration, I've encountered this output followed by the bot restarting and the whole process repeating.
I'm wondering whether the issue lies on my end or on your end. Help would be very much appreciated.

```
Cought command line args!
Using github: true
Logging in to github...
Attempting to use repository "testforcurseforgebot"
org.kohsuke.github.GHSearchBuilder$1@66c61024
Searching existing repos...
Found repo docker-D-Zone
Found repo docker-App-Collection
Found repo docker-ICEcoder
Found repo Wiki
Found repo docker-dcc
Found repo Dynmap-Renderdata
Found repo Griefed
Found repo Survive-Create-Prosper-4
Found repo docker-template-repo
Found repo docker-Curseforge-Bot
Found repo LSC64
Found repo Unicorn-HAT-HD-Various-Animations-and-Stuff
Found repo Unicorn-HAT-HD-CPU-Temperature
Found repo docker-Composerize
Found repo docker-nginxconfig.io
Found repo docker-triangulator
Found repo docker-SUI
Found repo Survive-Create-Prosper
Found repo testforcurseforgebot
Exception in thread "main" org.kohsuke.github.GHException: Failed to retrieve https://api.github.com/search/code?q=filename%3Acaches+extension%3Atxt+repo%3Atestforcurseforgebot+user%3AGriefed
        at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:529)
        at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:494)
        at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:55)
        at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
        at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
        at org.kohsuke.github.PagedSearchIterable.populate(PagedSearchIterable.java:46)
        at org.kohsuke.github.PagedSearchIterable.getTotalCount(PagedSearchIterable.java:35)
        at de.erdbeerbaerlp.curseforgeBot.Cfg.doesGHCacheExist(Cfg.java:121)
        at de.erdbeerbaerlp.curseforgeBot.Main.main(Main.java:80)
Cought command line args!
Using github: true
Logging in to github...
Attempting to use repository "testforcurseforgebot"
org.kohsuke.github.GHSearchBuilder$1@6ccdb29f
Searching existing repos...

```

Thanks in advance. Stay safe and stay healthy.

Cheers,
Griefed

**Comment by ErdbeerbaerLP** [comment]
Fixed in version 1.2.3
